
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - pytest

after_success:
- bash <(curl -s -s https://scripts.scantist.com/ci-travis.sh)
